filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
build:
    environment:
        php:
          version: 7.1.3
tools:
    external_code_coverage:
        timeout: 630
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
