filter:
    excluded_paths: [vendor/*, tests/*]
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
tools:
    external_code_coverage:
        timeout: 630
    php_code_sniffer:
        config:
            standard: "PSR2"
