Model\Coupon:
  type: entity
  table: coupons
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    description:
      type: text
    discount_percentage:
      type: integer
    discount_flat:
      type: integer
    redemption_key:
      type: string
    redemption_limit:
      type: integer
    redemption_expiration:
      type: date
    duration_in_months:
      type: integer
  oneToMany:
    coupon_redemptions:
      targetEntity: Model\CouponRedemption
      mappedBy: coupon
      cascade: ["persist"]
  manyToMany:
    subscription_plans:
      cascade: ["persist"]
      targetEntity: Model\SubscriptionPlan
      inversedBy: coupons
      joinTable:
        name: coupons_subscription_plans
        joinColumns:
          subscription_plan_id:
            referencedColumnName: id
        inverseJoinColumns:
          coupon_id:
            referencedColumnName: id
