Model\User:
  type: entity
  table: users
  fields:
    name:
      type: string
    email:
      type: string
  oneToMany:
    subscription_changes:
      targetEntity: Model\SubscriptionChange
      mappedBy: subscription
      cascade: ["persist"]
